services:
    _defaults:
        autowire: true
        autoconfigure: true

    MartenaSoft\ConsoleProfileBundle\:
        resource: '../../../src/'
        exclude:
            - '../../../src/DependencyInjection/'
            - '../../../src/Entity/'

    MartenaSoft\ConsoleProfileBundle\Service\ProfileDbService:
        arguments:
            $logDir: '%kernel.project_dir%/var/log' 